#!/bin/bash
#
# Tool for extracting decks from web pages and saving them in a forge readable format.
# 
# Works with:
#   channelfireball.com
#   mtggoldfish.com
#   tappedout.net

# Get url from clipboard.
url=$(xclip -selection clipboard -o)
if [[ -z $url ]]; then
    echo "No URL found in copy buffer"
    notify-send "No URL found in copy buffer"
    exit 1
fi

if [[ "$url" =~ .*channelfireball.* ]]; then
    echo "Identified ChannelFireball URL."
    /opt/kimbsy/bash/getdeck/./getdeck_from_cfb "$url"
elif [[ "$url" =~ .*mtggoldfish.* ]]; then
    echo "Identified MTGGoldfish URL."
    /opt/kimbsy/bash/getdeck/./getdeck_from_mtggf "$url"
elif [[ "$url" =~ .*tappedout.* ]]; then
    echo "Identified TappedOut URL."
    /opt/kimbsy/bash/getdeck/./getdeck_from_to "$url"
else
    echo "URL not recognised."
    exit 1
fi
