#!/bin/bash

. ~/.aws/dispatch.config

magurl=$(xclip -selection clipboard -o)
if [[ ! "$magurl" =~ magnet.* ]]; then
  notify-send "unrecognised magnet link format"
  exit
fi

displayname=$(echo "$magurl" | grep -oP "dn=\K.*?\d+" | cut -c1-20)

target=$(zenity --entry --title="Remote torrent" --text="Downloading torrent link: ${displayname} ... \n\nEnter target file name:")
if [ $? -ne 0 ]; then
  exit
fi

body=$(jq -n \
          --arg url "$magurl" \
          --arg target "$target" \
          '{
               action: "remote-torrent",
               data:
               {
                   url: $url,
                   target: $target
               }
           }')

aws sqs send-message --queue-url "$DISPATCH_QUEUE_URL" --message-group-id 1 --message-deduplication-id "$(date +%s%N)" --message-body "$body"  >> /tmp/output 2>&1
