#!/bin/bash

. ~/.aws/dispatch.config

magurl=$(xclip -selection clipboard -o)
displayname=$(echo "$magurl" | grep -oP "dn=\K.*?\d+" | cut -c1-20)

target=$(zenity --entry --title="Remote torrent" --text="Downloading torrent link: ${displayname} ... \n\nEnter target file name:")
if [ $? -ne 0 ]; then
  exit
fi

body=$(jq -n \
          --arg url "$magurl" \
          --arg target "$target" \
          '{
               action: "remote-torrent",
               url: $url,
               target: $target
           }')

aws sqs send-message --queue-url "$DISPATCH_QUEUE_URL" --message-body "$body"  >> /tmp/output 2>&1
